// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sadnerd.io.ATAS.OrderEventHub.Data;

#nullable disable

namespace sadnerd.io.ATAS.OrderEventHub.Migrations
{
    [DbContext(typeof(TradeCopyContext))]
    [Migration("20250414034812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("sadnerd.io.ATAS.OrderEventHub.Data.Models.AtasAccount", b =>
                {
                    b.Property<string>("AtasAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("AtasAccountId");

                    b.ToTable("AtasAccounts");
                });

            modelBuilder.Entity("sadnerd.io.ATAS.OrderEventHub.Data.Models.CopyStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtasAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtasContract")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractMultiplier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopstepAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TopstepContract")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AtasAccountId");

                    b.HasIndex("TopstepAccountId");

                    b.ToTable("CopyStrategies");
                });

            modelBuilder.Entity("sadnerd.io.ATAS.OrderEventHub.Data.Models.TopstepAccount", b =>
                {
                    b.Property<string>("TopstepAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("TopstepAccountId");

                    b.ToTable("TopstepAccount");
                });

            modelBuilder.Entity("sadnerd.io.ATAS.OrderEventHub.Data.Models.CopyStrategy", b =>
                {
                    b.HasOne("sadnerd.io.ATAS.OrderEventHub.Data.Models.AtasAccount", "AttasAccount")
                        .WithMany()
                        .HasForeignKey("AtasAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sadnerd.io.ATAS.OrderEventHub.Data.Models.TopstepAccount", "TopstepAccount")
                        .WithMany()
                        .HasForeignKey("TopstepAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttasAccount");

                    b.Navigation("TopstepAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
