// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sadnerd.io.ATAS.OrderEventHub.Data;

#nullable disable

namespace sadnerd.io.ATAS.OrderEventHub.Migrations
{
    [DbContext(typeof(OrderEventHubDbContext))]
    [Migration("20250916100203_AddApiCredentials")]
    partial class AddApiCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("sadnerd.io.ATAS.OrderEventHub.Data.Models.AtasAccount", b =>
                {
                    b.Property<string>("AtasAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("AtasAccountId");

                    b.ToTable("AtasAccounts");
                });

            modelBuilder.Entity("sadnerd.io.ATAS.OrderEventHub.Data.Models.CopyStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtasAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtasContract")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractMultiplier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectXAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectXContract")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AtasAccountId");

                    b.HasIndex("ProjectXAccountId");

                    b.ToTable("CopyStrategies");
                });

            modelBuilder.Entity("sadnerd.io.ATAS.OrderEventHub.Data.Models.ProjectXAccount", b =>
                {
                    b.Property<string>("ProjectXAccountId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApiCredentialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vendor")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectXAccountId");

                    b.HasIndex("ApiCredentialId");

                    b.ToTable("ProjectXAccounts");
                });

            modelBuilder.Entity("sadnerd.io.ATAS.OrderEventHub.Data.Models.ProjectXApiCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Vendor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Vendor", "DisplayName")
                        .IsUnique();

                    b.ToTable("ProjectXApiCredentials");
                });

            modelBuilder.Entity("sadnerd.io.ATAS.OrderEventHub.Data.Models.CopyStrategy", b =>
                {
                    b.HasOne("sadnerd.io.ATAS.OrderEventHub.Data.Models.AtasAccount", "AttasAccount")
                        .WithMany()
                        .HasForeignKey("AtasAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sadnerd.io.ATAS.OrderEventHub.Data.Models.ProjectXAccount", "ProjectXAccount")
                        .WithMany()
                        .HasForeignKey("ProjectXAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttasAccount");

                    b.Navigation("ProjectXAccount");
                });

            modelBuilder.Entity("sadnerd.io.ATAS.OrderEventHub.Data.Models.ProjectXAccount", b =>
                {
                    b.HasOne("sadnerd.io.ATAS.OrderEventHub.Data.Models.ProjectXApiCredential", "ApiCredential")
                        .WithMany("ProjectXAccounts")
                        .HasForeignKey("ApiCredentialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApiCredential");
                });

            modelBuilder.Entity("sadnerd.io.ATAS.OrderEventHub.Data.Models.ProjectXApiCredential", b =>
                {
                    b.Navigation("ProjectXAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
